name: Create and publish a Docker image

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}/quartz:latest .

      - name: Push Docker image to registry
        run: docker image push ${{ secrets.DOCKER_REPOSITORY }}/quartz:latest
